"""empty message

Revision ID: 1f596ac28de2
Revises: d86a37868d44
Create Date: 2021-01-04 04:28:24.815787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f596ac28de2'
down_revision = 'd86a37868d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'address', ['destination_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'destination_id')
    # ### end Alembic commands ###
