"""empty message

Revision ID: 62aa00edff3f
Revises: 1f596ac28de2
Create Date: 2021-01-06 15:30:20.703822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62aa00edff3f'
down_revision = '1f596ac28de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('destination', sa.String(length=200), nullable=True))
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.drop_column('order', 'destination_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('destination_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_ibfk_2', 'order', 'address', ['destination_id'], ['address_id'])
    op.drop_column('order', 'destination')
    # ### end Alembic commands ###
