"""empty message

Revision ID: 941026d587b8
Revises: dca40d0f845b
Create Date: 2021-01-01 19:14:48.919695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941026d587b8'
down_revision = 'dca40d0f845b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('fax', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('first_Name', sa.String(length=20), nullable=False),
    sa.Column('last_Name', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('photo_path', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('address')
    # ### end Alembic commands ###
