"""empty message

Revision ID: dad2a7ced51a
Revises: 62aa00edff3f
Create Date: 2021-01-06 15:56:56.185752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad2a7ced51a'
down_revision = '62aa00edff3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    # ### end Alembic commands ###
